apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  # Значення: "rootpassword", "todo_user", "todo_password" в base64
  MYSQL_ROOT_PASSWORD: bXNxbC1yb290LXBhc3N3b3Jk
  MYSQL_USER: dG9kb191c2Vy
  MYSQL_PASSWORD: dG9kb19wYXNzd29yZA==
